  #let bib-entry(count, name) = [
    #figure(kind: "cite", supplement: it => [#it], [[#count]], numbering: it => [])#label(name)
  ]

  #set figure(placement: top)
  #block(
    inset: 0.5em,
  grid(columns: (auto, 1fr), column-gutter: 1.6em, row-gutter: 1em,
    bib-entry("1", "bib1:gdpr"),
    [European Parliament and Council of the European Union, "Regulation (EU) 2016/679 of the European Parliament and of the Council." [Online]. Available: https://data.europa.eu/eli/reg/2016/679/oj],
    bib-entry("2", "bib1:ccpa"),
    [California State Legislature, “The California Consumer Privacy Act of 2018.” [Online]. Available: https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201720180AB375],
    bib-entry("3", "bib1:solid"),
    [E. Mansour et al., “A Demonstration of the Solid platform for Social Web Applications,” in Proceedings of the 25thInternational Conference Companion on World Wide Web,2016, pp. 223–226.],
    bib-entry("4", "bib1:bluesky"),
    [M. Kleppmann et al., “Bluesky and the AT Protocol: Usable Decentralized Social Media.” 2024.],
    bib-entry("5", "bib1:mastodon"),
    [M. Zignani, S. Gaito, and G. P. Rossi, “Follow the "Mastodon": Structure and Evolution of a Decentralized Online Social Network,” in Twelfth International AAAI Conference on Web and Social Media, 2018.],
    bib-entry("6", "bib1:nakamoto2008bitcoin"),
    [S. Nakamoto, “Bitcoin: A peer-to-peer electronic cash system,” Decentralized business review, 2008.],
    bib-entry("7", "bib1:hartig2016walking"),
    [O. Hartig and M. T. Özsu, “Walking without a map: Ranking-based traversal for querying linked data,” in The Semantic Web–ISWC 2016: 15th International Semantic Web Conference, Kobe, Japan, October 17–21, 2016, Proceedings, Part I 15, 2016, pp. 305–324.],
    bib-entry("8", "bib1:taelman-structure-assumptions"),
    [R. Taelman and R. Verborgh, “Link traversal query processing over decentralized environments with structural assumptions,” in International Semantic Web Conference, 2023, pp. 3–22.],
    bib-entry("9", "bib1:graphql"),
    [Facebook and GraphQL contributors, “GraphQL spec October 2021 Edition,” Oct. 2021.],
    bib-entry("10", "bib1:sparql"),
    [A. Seaborne and S. Harris, “SPARQL 1.1 Query Language,” Mar. 2013.],
    bib-entry("11", "bib1:solid-spec"),
    [S. Capadisli, T. Berners-Lee, R. Verborgh, and K. Kjernsmo, “Solid Protocol,” Dec. 2022.],
    bib-entry("12", "bib1:rdf"),
    [D. Wood, M. Lanthaler, and R. Cyganiak, “RDF 1.1 Concepts and Abstract Syntax,” Feb. 2014.],
    bib-entry("13", "bib1:ldp"),
    [S. Speicher, J. Arwe, and A. Malhotra, “Linked Data Platform 1.0,” Feb. 2015.],
    bib-entry("14", "bib1:wac"),
    [T. Berners-Lee, H. Story, and S. Capadisli, “Web Access Control,” May 2024.],
    bib-entry("15", "bib1:acp"),
    [M. Bosquet, “Access Control Policy (ACP),” May 2022.],
    bib-entry("16", "bib1:concise-bounded-description"),
    [P. Stickler, “CBD - Concise Bounded Description,” Jun. 2005.],
    bib-entry("17", "bib1:turtle"),
    [G. Carothers and E. Prud'hommeaux, “RDF 1.1 Turtle,” Feb. 2014.],
    bib-entry("18", "bib1:shex"),
    [T. Baker and E. Prud'hommeaux, “Shape Expressions (ShEx) 2.1 Primer,” Oct. 2019.],
    bib-entry("19", "bib1:shacl"),
    [H. Knublauch and D. Kontokostas, “Shapes Constraint Language (SHACL),” Jul. 201],
    bib-entry("20", "bib1:type-index"),
    [T. Turdean, J. Zucker, V. Balseiro, S. Capadisli, and T. Berners-Lee, “Type Indexes,” Jun. 2022.],
    bib-entry("21", "bib1:shape-tree"),
    [E. Prud'hommeaux and J. Bingham, “Shape Trees Speciﬁcation,” Dec. 2021],
    bib-entry("22", "bib1:ldbc"),
    [O. Erling et al., “The LDBC social network benchmark: Interactive workload,” in Proceedings of the 2015 ACM SIGMOD International Conference on Management of Data, 2015, pp. 619–630.],
    bib-entry("23", "bib1:subweb"),
    [B. Bogaerts, B. Ketsman, Y. Zeboudj, H. Aamer, R. Taelman, and R. Verborgh, “Link Traversal with Distributed Subweb Speciﬁcations,” in Proceedings of the 5th International Joint Conference on Rules and Reasoning, S. Moschoyiannis, R. Peñaloza, J. Vanthienen, A. Soylu, and D. Roman, Eds., in Lecture Notes in Computer Science, vol. 12851. Springer, Sep. 2021, pp. 62–79. doi: 10.1007/978-3-030-91167-6_5.],
    bib-entry("24", "bib1:whats-in-pod"),
    [R. Dedecker, W. Slabbinck, J. Wright, P. Hochstenbach, P. Colpaert, and R. Verborgh, “What’s in a Pod? A knowledge graph interpretation for the Solid ecosystem,” in 6th Workshop on Storing, Querying and Benchmarking Knowledge Graphs (QuWeDa) at ISWC 2022, 2022, pp. 81–96.],
    bib-entry("25", "bib1:vanherwergenderived"),
    [J. Van Herwegen and R. Verborgh, “Granular Access to Policy-Governed Linked Data via Partial Server-Side Query.”],
    bib-entry("26", "bib1:cap"),
    [A. Fox and E. A. Brewer, “Harvest, yield, and scalable tolerant systems,” in Proceedings of the Seventh Workshop on Hot Topics in Operating Systems, 1999, pp. 174–178.],
    bib-entry("27", "bib1:acid"),
    [J. Gray and others, “The transaction concept: Virtues and limitations,” in VLDB, 1981, pp. 144–154.],
    bib-entry("28", "bib1:base"),
    [D. Pritchett, “BASE: An ACID Alternative: In partitioned databases, trading some consistency for availability can lead to dramatic improvements in scalability.,” Queue, vol. 6, no. 3, pp. 48–55, 2008.],
    bib-entry("29", "bib1:crdt"),
    [M. Shapiro, N. Preguiça, C. Baquero, and M. Zawirski, “Conﬂict-free replicated data types,” in Stabilization, Safety, and Security of Distributed Systems: 13th International Symposium, SSS 2011, Grenoble, France, October 10-12, 2011. Proceedings 13, 2011, pp. 386–400.],
    bib-entry("30", "bib1:continous-cap"),
    [E. Brewer, “CAP twelve years later: How the "rules" have changed,” Computer, vol. 45, no. 2, pp. 23–29, Feb. 2012, doi: 10.1109/MC.2012.37.],
    bib-entry("31", "bib1:links-can-break"),
    [T. Berners-Lee, R. Cailliau, J.-F. Groﬀ, and B. Pollermann, “World-Wide Web: the information universe,” Internet Research, vol. 2, no. 1, pp. 52–58, 1992.],
  )
)